Description:
  This template builds a Webapp application on an AutoScaling group, behind an Application Load Balancer, with a CodeDeploy application.

Parameters:
  AWSInfraStack:
    Description: Name of the infrastructure CloudFormation stack .
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: AWSInfraStack
  Stage:
    Description: Release stage
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: Prod

Resources:
  DeploymentGroup:
    Type: "AWS::CodeDeploy::DeploymentGroup"
    Properties:
      DeploymentGroupName: !Join
      - '-'
      - - !Ref 'AWS::StackName'
        - DeploymentGroup
      ApplicationName:
        Fn::ImportValue:
          !Sub "${AWSInfraStack}:CodeDeployApplication"
      ServiceRoleArn:
        Fn::ImportValue:
          !Sub "${AWSInfraStack}:CodeDeployRole"
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      AutoScalingGroups:
      - Ref: AutoScalingGroup

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      MinSize: 1
      MaxSize: 3
      LaunchConfigurationName:
        Fn::ImportValue:
          !Sub "${AWSInfraStack}:LaunchConfig"
      VPCZoneIdentifier:
        Fn::Split:
        - ","
        - Fn::ImportValue:
            !Sub "${AWSInfraStack}:PublicSubnets"
      TargetGroupARNs:
        - Ref: LoadBalancerTargetGroup
      Tags:
        - Key: Name
          Value: !Join
          - "-"
          - - Fn::ImportValue:
                !Sub "${AWSInfraStack}:ApplicationName"
            - !Ref Stage
          PropagateAtLaunch: true

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        -
          Type: forward
          TargetGroupArn:
            Ref: LoadBalancerTargetGroup
      LoadBalancerArn:
        Ref: LoadBalancer
      Port: 80
      Protocol: HTTP

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        Fn::Split:
        - ","
        - Fn::ImportValue:
            !Sub "${AWSInfraStack}:PublicSubnets"
      SecurityGroups:
        - Fn::ImportValue:
            !Sub "${AWSInfraStack}:PublicHttpIngressSecurityGroup"

  LoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      VpcId:
        Fn::ImportValue:
          !Sub "${AWSInfraStack}:VPC"

Outputs:
  Url:
    Description: Webapp application URL
    Value:
      Fn::Sub: 'http://${LoadBalancer.DNSName}'
  DeploymentGroup:
    Description: Webapp application deployment group
    Value: !Ref DeploymentGroup
